name: Docker Image CI

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark:
          - 3.0.1
          - 2.4.5
          - 2.4.4
          - 2.4.3
          - 2.4.2
          - 2.4.1
          - 2.4.0
          - 2.3.2
          - 2.3.1
          - 2.3.0
          - 2.2.2
          - 2.2.1
          - 2.2.0
          - 2.1.3
          - 2.1.2
          - 2.1.1
          - 2.1.0
          - 2.0.2
          - 2.0.1
          - 2.0.0
          - 2.0.0
        livy: [0.5.0, 0.6.0, 0.7.0]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Get Apache path
        id: apache
        env:
          LIVY: ${{ matrix.livy }}
        run: |
          if [ $LIVY == '0.5.0' ]
          then
            echo "::set-output name=path::"
          else
            echo "::set-output name=path::apache-"
          fi
      - name: Push to Dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: davlum/livy
          build_args: SPARK_VERSION=${{ matrix.spark }},LIVY_VERSION=${{ matrix.livy }},APACHE=${{ steps.apache.outputs.path }}
          tags: ${{ matrix.livy }}-spark${{ matrix.spark }}

